name: Deploy Prod

on:
  push:
    branches: [main]

jobs:
  Deploy-Prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install
        run: npm install --force
      - name: Build
        run: npm run build --force
      - name: Test
        run: npm run test