name: deployment prod

on: [push]

jobs:
  run_pipe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install packages
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test